# Server configurations
server:
  host: "localhost"
  port: "8000"

# Database credentials
database:
  uri: "mongodb://indoquran:indoquran@mongodb:27017/indoquran"
  dbname: "indoquran"

# Redis configurations
cache:
  uri: "redis://redis:6379/0"
  addr: "redis:6379"
  pass: ""
  ttl: 12 # time to leave in hour value

# Session configurations
session:
  name: "indoquranSession"
  secret: "XWYn86vz9m"
  user_id: "indoquranUserID"

secrets:
  geolication: "d6570d658eff4d299890b61907969c3f"
  hmac: "3E2CB5CDA258BFA1D62BDB5A4BF53"

email:
  smtp: "smtp.gmail.com"
  port: 587
  from: "admin@indoquran.id"
  user: "kontak@indoquran.web.id"
  pass: "Karawangman123"
