# Server configurations
server:
  port: "8000"

# Database credentials
database:
  uri: "mongodb://indoquran:indoquran@localhost:27017/indoquran"
  dbname: "indoquran"

# Redis configurations
cache:
  uri: "redis://localhost:6379/0"
  addr: "localhost:6379"
  pass: ""
  ttl: 24 # time to leave in hour value

# Session configurations
session:
  name: "indoquranSession"
  secret: "kSuo2RZIyz"
  user_id: "indoquranUserID"

secrets:
  geolication: "d6570d658eff4d299890b61907969c3f"

email:
  smtp: "smtp.zoho.com"
  port: 465
  from: "admin@indoquran.id"
  user: "admin@indoquran.id"
  pass: "Karawangman123"
