# Server configurations
server:
  port: "8080"

# Database credentials
database:
  # uri: "mongodb://indoquran:indoquran@localhost:27017/?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=indoquran&authMechanism=SCRAM-SHA-256"
  uri: "mongodb+srv://nova:admin123@cluster0.df2xr.mongodb.net/admin?replicaSet=atlas-vi2i0z-shard-0&readPreference=primary&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1"
  dbname: "indoquran"

# Redis configurations
cache:
  uri: "redis://localhost:6379/0"
  addr: "localhost:6379"
  pass: ""
  ttl: 12 # time to leave in hour value

# Session configurations
session:
  name: "indoquranSession"
  secret: "2y73jVhbT9"
  user_id: "indoquranUserID"
