# Server configurations
server:
  host: "localhost"
  port: "8080"

# Database credentials
database:
  uri: "mongodb+srv://nova:admin123@cluster0.df2xr.mongodb.net/admin?replicaSet=atlas-vi2i0z-shard-0&readPreference=primary&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1"
  dbname: "indoquran"

# Redis configurations
cache:
  uri: "redis://localhost:6379/0"
  addr: "localhost:6379"
  pass: ""
  ttl: 12 # time to leave in hour value

# Session configurations
session:
  name: "indoquranSession"
  secret: "2y73jVhbT9"
  user_id: "indoquranUserID"

secrets:
  geolication: "d6570d658eff4d299890b61907969c3f"
  hmac: "393B8954C347B2669D51929A6E759"

email:
  smtp: "smtp.gmail.com"
  port: 587
  from: "admin@indoquran.id"
  user: "kontak@indoquran.web.id"
  pass: "Karawangman123"
