# Database Configuration
DB_USER: d9cyf2h0sxrx0y32
DB_PASSWORD: osfy2oegj2jxvf5t
DB_HOST: q68u8b2buodpme2n.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
DB_PORT: 3306
DB_NAME: ed7k8l4v6cl8qfmd

# Redis Configuration
REDIS_HOST: redis-12111.c257.us-east-1-3.ec2.redns.redis-cloud.com
REDIS_PORT: 12111
REDIS_PASSWORD: ''
REDIS_DB: redis-rediscloud-clean-11866

# API Configuration
API_PORT: 80
RATE_LIMIT_FILE: ./internal/config/rate_limit.yml