# Database Configuration
DB_USER: root
DB_PASSWORD: root
DB_HOST: localhost
DB_PORT: 3306
DB_NAME: indoquran

# Redis Configuration
REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_PASSWORD: ''
REDIS_DB: 0

# API Configuration
API_PORT: 8090
RATE_LIMIT_FILE: ./internal/config/rate_limit.yml